<?php

namespace Database\Seeders;

use App\Models\Language;
use Illuminate\Database\Seeder;

class LanguageSeeder extends Seeder
{
    public function run(): void
    {
        $en = [
            'nav.home' => 'Home', 'nav.tools' => 'Tools', 'nav.pricing' => 'Pricing', 'nav.contact' => 'Contact',
            'nav.signin' => 'Sign in', 'nav.getstarted' => 'Get started', 'nav.admin' => 'Admin panel',
            'nav.account' => 'My account', 'nav.signout' => 'Sign out',
            'hero.badge' => 'All your AI tools, one workspace',
            'hero.title' => 'Create images, words & voice with',
            'hero.subtitle' => 'Generate visuals, write content, translate anything, chat with documents, remove backgrounds, and produce voiceovers — one dashboard, one subscription.',
            'hero.start' => 'Start creating', 'hero.explore' => 'Explore the tools',
            'hero.open_tools' => 'Open your tools', 'hero.see_plans' => 'See plans',
            'stats.tools' => 'AI tools included', 'stats.languages' => 'Languages supported',
            'stats.subscription' => 'Simple subscription', 'stats.ideas' => 'Ideas to explore',
            'toolkit.title' => 'The toolkit', 'toolkit.subtitle' => 'Click any tool to jump straight in.',
            'toolkit.try' => 'Try it', 'toolkit.open' => 'Open tool',
            'how.title' => 'How it works',
            'how.s1.title' => 'Pick a tool', 'how.s1.text' => 'Choose from image generation, writing, translation, documents, background removal, or voiceovers.',
            'how.s2.title' => 'Describe what you want', 'how.s2.text' => 'Type a prompt, upload a file, or paste your text. Fine-tune with styles, tones, and voices.',
            'how.s3.title' => 'Use it anywhere', 'how.s3.text' => 'Download your images and audio, or copy your text — it belongs to you.',
            'testimonials.title' => 'Loved by creators',
            'pricing.title' => 'Pricing', 'pricing.subtitle' => 'Every plan includes every tool. Credits reset each billing cycle. Cancel anytime.',
            'pricing.month' => 'month', 'pricing.year' => 'year', 'pricing.choose' => 'Choose plan',
            'pricing.current' => 'Current plan', 'pricing.popular' => 'Most popular', 'pricing.getstarted' => 'Get started',
            'cta.title' => 'Ready to create?',
            'cta.subtitle' => "Set up your account in under a minute — browse the studio free, upgrade when you're ready.",
            'cta.button' => 'Create free account',
            'gate.login.title' => 'Sign in to use this tool',
            'gate.login.text' => "Create a free account or sign in — you'll be brought right back here.",
            'gate.login.register' => 'Create account',
            'gate.plans.title' => 'Choose a plan to unlock the tools',
            'gate.plans.text' => 'Every plan includes every tool — pick the credit level that fits.',
            'tools.title' => 'Pick a tool, start creating',
            'tools.subtitle' => 'Everything is included in every plan — your credits work across the whole toolkit.',
            'free.badge' => 'Free', 'free.uses' => 'free uses',
            'footer.rights' => 'All rights reserved.',
            'common.loading' => 'Loading…',
        ];

        $es = [
            'nav.home' => 'Inicio', 'nav.tools' => 'Herramientas', 'nav.pricing' => 'Precios', 'nav.contact' => 'Contacto',
            'nav.signin' => 'Iniciar sesión', 'nav.getstarted' => 'Comenzar', 'nav.admin' => 'Panel de administración',
            'nav.account' => 'Mi cuenta', 'nav.signout' => 'Cerrar sesión',
            'hero.badge' => 'Todas tus herramientas de IA, un solo espacio',
            'hero.title' => 'Crea imágenes, textos y voz con',
            'hero.subtitle' => 'Genera imágenes, escribe contenido, traduce lo que quieras, consulta documentos, elimina fondos y produce locuciones — un panel, una suscripción.',
            'hero.start' => 'Empieza a crear', 'hero.explore' => 'Explorar herramientas',
            'hero.open_tools' => 'Abrir tus herramientas', 'hero.see_plans' => 'Ver planes',
            'stats.tools' => 'Herramientas de IA incluidas', 'stats.languages' => 'Idiomas disponibles',
            'stats.subscription' => 'Suscripción simple', 'stats.ideas' => 'Ideas por explorar',
            'toolkit.title' => 'Las herramientas', 'toolkit.subtitle' => 'Haz clic en cualquier herramienta para empezar.',
            'toolkit.try' => 'Probar', 'toolkit.open' => 'Abrir herramienta',
            'how.title' => 'Cómo funciona',
            'how.s1.title' => 'Elige una herramienta', 'how.s1.text' => 'Generación de imágenes, redacción, traducción, documentos, eliminación de fondos o locuciones.',
            'how.s2.title' => 'Describe lo que quieres', 'how.s2.text' => 'Escribe una instrucción, sube un archivo o pega tu texto. Ajusta estilos, tonos y voces.',
            'how.s3.title' => 'Úsalo donde quieras', 'how.s3.text' => 'Descarga tus imágenes y audios, o copia tu texto — es tuyo.',
            'testimonials.title' => 'Amado por creadores',
            'pricing.title' => 'Precios', 'pricing.subtitle' => 'Cada plan incluye todas las herramientas. Los créditos se renuevan cada ciclo. Cancela cuando quieras.',
            'pricing.month' => 'mes', 'pricing.year' => 'año', 'pricing.choose' => 'Elegir plan',
            'pricing.current' => 'Plan actual', 'pricing.popular' => 'Más popular', 'pricing.getstarted' => 'Comenzar',
            'cta.title' => '¿Listo para crear?',
            'cta.subtitle' => 'Configura tu cuenta en menos de un minuto — explora gratis y mejora cuando quieras.',
            'cta.button' => 'Crear cuenta gratis',
            'gate.login.title' => 'Inicia sesión para usar esta herramienta',
            'gate.login.text' => 'Crea una cuenta gratis o inicia sesión — volverás aquí directamente.',
            'gate.login.register' => 'Crear cuenta',
            'gate.plans.title' => 'Elige un plan para desbloquear las herramientas',
            'gate.plans.text' => 'Cada plan incluye todas las herramientas — elige el nivel de créditos que necesites.',
            'tools.title' => 'Elige una herramienta y empieza a crear',
            'tools.subtitle' => 'Todo está incluido en cada plan — tus créditos sirven para todas las herramientas.',
            'free.badge' => 'Gratis', 'free.uses' => 'usos gratis',
            'footer.rights' => 'Todos los derechos reservados.',
            'common.loading' => 'Cargando…',
        ];

        $zh = [
            'nav.home' => '首页', 'nav.tools' => '工具', 'nav.pricing' => '价格', 'nav.contact' => '联系我们',
            'nav.signin' => '登录', 'nav.getstarted' => '立即开始', 'nav.admin' => '管理后台',
            'nav.account' => '我的账户', 'nav.signout' => '退出登录',
            'hero.badge' => '所有 AI 工具，一个工作台',
            'hero.title' => '用它创作图像、文字与语音：',
            'hero.subtitle' => '生成图片、撰写内容、翻译任何文本、与文档对话、去除背景、制作配音 — 一个平台，一份订阅。',
            'hero.start' => '开始创作', 'hero.explore' => '探索工具',
            'hero.open_tools' => '打开我的工具', 'hero.see_plans' => '查看套餐',
            'stats.tools' => '内置 AI 工具', 'stats.languages' => '支持的语言',
            'stats.subscription' => '简单订阅', 'stats.ideas' => '无限创意',
            'toolkit.title' => '工具箱', 'toolkit.subtitle' => '点击任意工具立即开始。',
            'toolkit.try' => '试一试', 'toolkit.open' => '打开工具',
            'how.title' => '使用方法',
            'how.s1.title' => '选择工具', 'how.s1.text' => '图像生成、写作、翻译、文档问答、背景去除或配音，任你选择。',
            'how.s2.title' => '描述你的需求', 'how.s2.text' => '输入提示词、上传文件或粘贴文本，并微调风格、语气和声音。',
            'how.s3.title' => '随处使用', 'how.s3.text' => '下载图片和音频，或复制文本 — 成果归你所有。',
            'testimonials.title' => '深受创作者喜爱',
            'pricing.title' => '价格', 'pricing.subtitle' => '每个套餐包含所有工具。额度每个周期重置，随时可取消。',
            'pricing.month' => '月', 'pricing.year' => '年', 'pricing.choose' => '选择套餐',
            'pricing.current' => '当前套餐', 'pricing.popular' => '最受欢迎', 'pricing.getstarted' => '立即开始',
            'cta.title' => '准备好创作了吗？',
            'cta.subtitle' => '一分钟内完成注册 — 免费浏览，随时升级。',
            'cta.button' => '免费创建账户',
            'gate.login.title' => '登录后即可使用此工具',
            'gate.login.text' => '免费注册或登录 — 之后会直接回到这里。',
            'gate.login.register' => '创建账户',
            'gate.plans.title' => '选择套餐以解锁全部工具',
            'gate.plans.text' => '每个套餐都包含所有工具 — 选择适合你的额度。',
            'tools.title' => '选择工具，开始创作',
            'tools.subtitle' => '所有内容都包含在每个套餐中 — 额度通用于全部工具。',
            'free.badge' => '免费', 'free.uses' => '次免费使用',
            'footer.rights' => '版权所有。',
            'common.loading' => '加载中…',
        ];

        $ar = [
            'nav.home' => 'الرئيسية', 'nav.tools' => 'الأدوات', 'nav.pricing' => 'الأسعار', 'nav.contact' => 'اتصل بنا',
            'nav.signin' => 'تسجيل الدخول', 'nav.getstarted' => 'ابدأ الآن', 'nav.admin' => 'لوحة الإدارة',
            'nav.account' => 'حسابي', 'nav.signout' => 'تسجيل الخروج',
            'hero.badge' => 'كل أدوات الذكاء الاصطناعي في مساحة واحدة',
            'hero.title' => 'أنشئ الصور والنصوص والصوت مع',
            'hero.subtitle' => 'أنشئ الصور، اكتب المحتوى، ترجم أي نص، تحدث مع مستنداتك، أزل الخلفيات، وأنتج التعليقات الصوتية — لوحة واحدة واشتراك واحد.',
            'hero.start' => 'ابدأ الإبداع', 'hero.explore' => 'استكشف الأدوات',
            'hero.open_tools' => 'افتح أدواتك', 'hero.see_plans' => 'عرض الباقات',
            'stats.tools' => 'أدوات ذكاء اصطناعي', 'stats.languages' => 'لغة مدعومة',
            'stats.subscription' => 'اشتراك بسيط', 'stats.ideas' => 'أفكار بلا حدود',
            'toolkit.title' => 'مجموعة الأدوات', 'toolkit.subtitle' => 'انقر على أي أداة للبدء فورًا.',
            'toolkit.try' => 'جرّبها', 'toolkit.open' => 'افتح الأداة',
            'how.title' => 'كيف يعمل',
            'how.s1.title' => 'اختر أداة', 'how.s1.text' => 'إنشاء الصور، الكتابة، الترجمة، المستندات، إزالة الخلفيات أو التعليق الصوتي.',
            'how.s2.title' => 'صف ما تريد', 'how.s2.text' => 'اكتب وصفًا، ارفع ملفًا أو الصق نصك. اضبط الأنماط والنبرات والأصوات.',
            'how.s3.title' => 'استخدمه في أي مكان', 'how.s3.text' => 'حمّل صورك وملفاتك الصوتية أو انسخ نصوصك — كلها ملك لك.',
            'testimonials.title' => 'يحبه المبدعون',
            'pricing.title' => 'الأسعار', 'pricing.subtitle' => 'كل باقة تشمل جميع الأدوات. يتجدد الرصيد كل دورة. يمكنك الإلغاء في أي وقت.',
            'pricing.month' => 'شهر', 'pricing.year' => 'سنة', 'pricing.choose' => 'اختر الباقة',
            'pricing.current' => 'باقتك الحالية', 'pricing.popular' => 'الأكثر شيوعًا', 'pricing.getstarted' => 'ابدأ الآن',
            'cta.title' => 'مستعد للإبداع؟',
            'cta.subtitle' => 'أنشئ حسابك في أقل من دقيقة — تصفح مجانًا وقم بالترقية متى شئت.',
            'cta.button' => 'أنشئ حسابًا مجانيًا',
            'gate.login.title' => 'سجّل الدخول لاستخدام هذه الأداة',
            'gate.login.text' => 'أنشئ حسابًا مجانيًا أو سجّل الدخول — ستعود إلى هنا مباشرة.',
            'gate.login.register' => 'إنشاء حساب',
            'gate.plans.title' => 'اختر باقة لفتح جميع الأدوات',
            'gate.plans.text' => 'كل باقة تشمل جميع الأدوات — اختر مستوى الرصيد المناسب لك.',
            'tools.title' => 'اختر أداة وابدأ الإبداع',
            'tools.subtitle' => 'كل شيء مشمول في كل باقة — رصيدك يعمل مع جميع الأدوات.',
            'free.badge' => 'مجاني', 'free.uses' => 'استخدامات مجانية',
            'footer.rights' => 'جميع الحقوق محفوظة.',
            'common.loading' => 'جارٍ التحميل…',
        ];

        $fr = [
            'nav.home' => 'Accueil', 'nav.tools' => 'Outils', 'nav.pricing' => 'Tarifs', 'nav.contact' => 'Contact',
            'nav.signin' => 'Connexion', 'nav.getstarted' => 'Commencer', 'nav.admin' => "Panneau d'administration",
            'nav.account' => 'Mon compte', 'nav.signout' => 'Déconnexion',
            'hero.badge' => 'Tous vos outils IA, un seul espace',
            'hero.title' => 'Créez images, textes et voix avec',
            'hero.subtitle' => 'Générez des visuels, rédigez du contenu, traduisez tout, interrogez vos documents, supprimez les arrière-plans et produisez des voix off — un tableau de bord, un abonnement.',
            'hero.start' => 'Commencer à créer', 'hero.explore' => 'Découvrir les outils',
            'hero.open_tools' => 'Ouvrir vos outils', 'hero.see_plans' => 'Voir les offres',
            'stats.tools' => 'Outils IA inclus', 'stats.languages' => 'Langues prises en charge',
            'stats.subscription' => 'Abonnement simple', 'stats.ideas' => 'Idées à explorer',
            'toolkit.title' => 'La boîte à outils', 'toolkit.subtitle' => 'Cliquez sur un outil pour commencer.',
            'toolkit.try' => 'Essayer', 'toolkit.open' => "Ouvrir l'outil",
            'how.title' => 'Comment ça marche',
            'how.s1.title' => 'Choisissez un outil', 'how.s1.text' => "Génération d'images, rédaction, traduction, documents, suppression d'arrière-plan ou voix off.",
            'how.s2.title' => 'Décrivez ce que vous voulez', 'how.s2.text' => 'Saisissez une consigne, téléversez un fichier ou collez votre texte. Ajustez styles, tons et voix.',
            'how.s3.title' => 'Utilisez-le partout', 'how.s3.text' => 'Téléchargez vos images et audios, ou copiez vos textes — ils vous appartiennent.',
            'testimonials.title' => 'Adoré par les créateurs',
            'pricing.title' => 'Tarifs', 'pricing.subtitle' => 'Chaque offre inclut tous les outils. Les crédits se renouvellent à chaque cycle. Annulez à tout moment.',
            'pricing.month' => 'mois', 'pricing.year' => 'an', 'pricing.choose' => "Choisir l'offre",
            'pricing.current' => 'Offre actuelle', 'pricing.popular' => 'La plus populaire', 'pricing.getstarted' => 'Commencer',
            'cta.title' => 'Prêt à créer ?',
            'cta.subtitle' => 'Créez votre compte en moins d\'une minute — explorez gratuitement, passez au niveau supérieur quand vous voulez.',
            'cta.button' => 'Créer un compte gratuit',
            'gate.login.title' => 'Connectez-vous pour utiliser cet outil',
            'gate.login.text' => 'Créez un compte gratuit ou connectez-vous — vous reviendrez directement ici.',
            'gate.login.register' => 'Créer un compte',
            'gate.plans.title' => 'Choisissez une offre pour débloquer les outils',
            'gate.plans.text' => 'Chaque offre inclut tous les outils — choisissez le niveau de crédits qui vous convient.',
            'tools.title' => 'Choisissez un outil, commencez à créer',
            'tools.subtitle' => 'Tout est inclus dans chaque offre — vos crédits fonctionnent sur toute la boîte à outils.',
            'free.badge' => 'Gratuit', 'free.uses' => 'utilisations gratuites',
            'footer.rights' => 'Tous droits réservés.',
            'common.loading' => 'Chargement…',
        ];


        // ── Full-site coverage: auth, contact, account, workspace, tool names ──
        $ext_en = [
            'auth.welcome' => 'Welcome back', 'auth.signin_sub' => 'Sign in to your studio.',
            'auth.email' => 'Email', 'auth.password' => 'Password', 'auth.signin_btn' => 'Sign in',
            'auth.no_account' => "Don't have an account?", 'auth.create_title' => 'Create your account',
            'auth.name' => 'Full name', 'auth.age' => 'Age (optional)', 'auth.confirm' => 'Confirm password',
            'auth.register_btn' => 'Create account', 'auth.have_account' => 'Already have an account?',
            'auth.check_email' => 'Check your email', 'auth.check_email_text' => 'We sent a verification link to', 'auth.goto_signin' => 'Go to sign in',
            'contact.title' => 'Get in touch', 'contact.subtitle' => "Questions, ideas, or trouble with a tool — send a message and we'll get back to you.",
            'contact.name' => 'Your name', 'contact.email' => 'Your email', 'contact.subject' => 'Subject',
            'contact.message' => 'Your message', 'contact.send' => 'Send message', 'contact.sent' => 'Message sent — thank you!',
            'account.title' => 'My account', 'account.profile' => 'Profile', 'account.plan' => 'Your plan',
            'account.credits' => 'Credits this cycle', 'account.no_plan' => "You don't have a plan yet.",
            'account.choose_plan' => 'Choose a plan', 'account.cancel' => 'Cancel subscription',
            'ws.back' => 'All tools', 'ws.result' => 'Result', 'ws.download' => 'Download', 'ws.copy' => 'Copy',
            'ws.copied' => 'Copied!', 'ws.working' => 'Working…', 'ws.previous' => 'Previous results',
            'ws.empty' => 'Your results will appear here.',
            'tool.ai-image-generator.name' => 'AI Image Generator', 'tool.ai-image-generator.desc' => 'Turn words into stunning visuals.',
            'tool.ai-content-writer.name' => 'AI Content Writer', 'tool.ai-content-writer.desc' => 'Blogs, ads, emails — written in seconds.',
            'tool.ai-translator.name' => 'AI Translator', 'tool.ai-translator.desc' => 'Natural translations in 12+ languages.',
            'tool.ai-document-assistant.name' => 'AI Document Assistant', 'tool.ai-document-assistant.desc' => 'Upload a document and ask it anything.',
            'tool.ai-background-removal.name' => 'AI Background Removal', 'tool.ai-background-removal.desc' => 'Clean cutouts in one click.',
            'tool.ai-text-to-audio.name' => 'AI Text to Audio', 'tool.ai-text-to-audio.desc' => 'Lifelike voiceovers from text.',
            'tool.ai-chat-assistant.name' => 'AI Chat Assistant', 'tool.ai-chat-assistant.desc' => 'Ask anything — your everyday AI helper.',
            'tool.ai-text-rewriter.name' => 'AI Grammar & Rewriter', 'tool.ai-text-rewriter.desc' => 'Fix grammar or rewrite text in one click.',
            'tool.ai-summarizer.name' => 'AI Summarizer', 'tool.ai-summarizer.desc' => 'Long text in, key points out.',
        ];
        $ext_es = [
            'auth.welcome' => 'Bienvenido de nuevo', 'auth.signin_sub' => 'Inicia sesión en tu estudio.',
            'auth.email' => 'Correo electrónico', 'auth.password' => 'Contraseña', 'auth.signin_btn' => 'Iniciar sesión',
            'auth.no_account' => '¿No tienes cuenta?', 'auth.create_title' => 'Crea tu cuenta',
            'auth.name' => 'Nombre completo', 'auth.age' => 'Edad (opcional)', 'auth.confirm' => 'Confirmar contraseña',
            'auth.register_btn' => 'Crear cuenta', 'auth.have_account' => '¿Ya tienes cuenta?',
            'auth.check_email' => 'Revisa tu correo', 'auth.check_email_text' => 'Enviamos un enlace de verificación a', 'auth.goto_signin' => 'Ir a iniciar sesión',
            'contact.title' => 'Contáctanos', 'contact.subtitle' => 'Preguntas, ideas o problemas con una herramienta — envía un mensaje y te responderemos.',
            'contact.name' => 'Tu nombre', 'contact.email' => 'Tu correo', 'contact.subject' => 'Asunto',
            'contact.message' => 'Tu mensaje', 'contact.send' => 'Enviar mensaje', 'contact.sent' => '¡Mensaje enviado — gracias!',
            'account.title' => 'Mi cuenta', 'account.profile' => 'Perfil', 'account.plan' => 'Tu plan',
            'account.credits' => 'Créditos de este ciclo', 'account.no_plan' => 'Aún no tienes un plan.',
            'account.choose_plan' => 'Elegir un plan', 'account.cancel' => 'Cancelar suscripción',
            'ws.back' => 'Todas las herramientas', 'ws.result' => 'Resultado', 'ws.download' => 'Descargar', 'ws.copy' => 'Copiar',
            'ws.copied' => '¡Copiado!', 'ws.working' => 'Procesando…', 'ws.previous' => 'Resultados anteriores',
            'ws.empty' => 'Tus resultados aparecerán aquí.',
            'tool.ai-image-generator.name' => 'Generador de Imágenes IA', 'tool.ai-image-generator.desc' => 'Convierte palabras en imágenes impresionantes.',
            'tool.ai-content-writer.name' => 'Redactor de Contenido IA', 'tool.ai-content-writer.desc' => 'Blogs, anuncios, correos — escritos en segundos.',
            'tool.ai-translator.name' => 'Traductor IA', 'tool.ai-translator.desc' => 'Traducciones naturales en más de 12 idiomas.',
            'tool.ai-document-assistant.name' => 'Asistente de Documentos IA', 'tool.ai-document-assistant.desc' => 'Sube un documento y pregúntale lo que quieras.',
            'tool.ai-background-removal.name' => 'Eliminador de Fondos IA', 'tool.ai-background-removal.desc' => 'Recortes limpios en un clic.',
            'tool.ai-text-to-audio.name' => 'Texto a Audio IA', 'tool.ai-text-to-audio.desc' => 'Voces realistas a partir de texto.',
            'tool.ai-chat-assistant.name' => 'Asistente de Chat IA', 'tool.ai-chat-assistant.desc' => 'Pregunta lo que sea — tu ayudante diario.',
            'tool.ai-text-rewriter.name' => 'Gramática y Reescritura IA', 'tool.ai-text-rewriter.desc' => 'Corrige o reescribe textos en un clic.',
            'tool.ai-summarizer.name' => 'Resumidor IA', 'tool.ai-summarizer.desc' => 'Texto largo dentro, ideas clave fuera.',
        ];
        $ext_zh = [
            'auth.welcome' => '欢迎回来', 'auth.signin_sub' => '登录你的工作台。',
            'auth.email' => '邮箱', 'auth.password' => '密码', 'auth.signin_btn' => '登录',
            'auth.no_account' => '还没有账户？', 'auth.create_title' => '创建你的账户',
            'auth.name' => '姓名', 'auth.age' => '年龄（可选）', 'auth.confirm' => '确认密码',
            'auth.register_btn' => '创建账户', 'auth.have_account' => '已有账户？',
            'auth.check_email' => '请查收邮件', 'auth.check_email_text' => '我们已将验证链接发送至', 'auth.goto_signin' => '前往登录',
            'contact.title' => '联系我们', 'contact.subtitle' => '有问题、想法或工具故障 — 给我们留言，我们会尽快回复。',
            'contact.name' => '你的姓名', 'contact.email' => '你的邮箱', 'contact.subject' => '主题',
            'contact.message' => '留言内容', 'contact.send' => '发送留言', 'contact.sent' => '留言已发送 — 谢谢！',
            'account.title' => '我的账户', 'account.profile' => '个人资料', 'account.plan' => '我的套餐',
            'account.credits' => '本周期额度', 'account.no_plan' => '你还没有套餐。',
            'account.choose_plan' => '选择套餐', 'account.cancel' => '取消订阅',
            'ws.back' => '全部工具', 'ws.result' => '结果', 'ws.download' => '下载', 'ws.copy' => '复制',
            'ws.copied' => '已复制！', 'ws.working' => '处理中…', 'ws.previous' => '历史结果',
            'ws.empty' => '你的结果将显示在这里。',
            'tool.ai-image-generator.name' => 'AI 图像生成器', 'tool.ai-image-generator.desc' => '将文字变成精美图像。',
            'tool.ai-content-writer.name' => 'AI 内容写作', 'tool.ai-content-writer.desc' => '博客、广告、邮件 — 几秒写好。',
            'tool.ai-translator.name' => 'AI 翻译', 'tool.ai-translator.desc' => '12+ 种语言的自然翻译。',
            'tool.ai-document-assistant.name' => 'AI 文档助手', 'tool.ai-document-assistant.desc' => '上传文档，随便提问。',
            'tool.ai-background-removal.name' => 'AI 抠图', 'tool.ai-background-removal.desc' => '一键干净去除背景。',
            'tool.ai-text-to-audio.name' => 'AI 文字转语音', 'tool.ai-text-to-audio.desc' => '逼真的语音配音。',
            'tool.ai-chat-assistant.name' => 'AI 聊天助手', 'tool.ai-chat-assistant.desc' => '想问就问 — 你的日常 AI 帮手。',
            'tool.ai-text-rewriter.name' => 'AI 语法与改写', 'tool.ai-text-rewriter.desc' => '一键纠错或改写文本。',
            'tool.ai-summarizer.name' => 'AI 摘要', 'tool.ai-summarizer.desc' => '长文进，要点出。',
        ];
        $ext_ar = [
            'auth.welcome' => 'مرحبًا بعودتك', 'auth.signin_sub' => 'سجّل الدخول إلى الاستوديو الخاص بك.',
            'auth.email' => 'البريد الإلكتروني', 'auth.password' => 'كلمة المرور', 'auth.signin_btn' => 'تسجيل الدخول',
            'auth.no_account' => 'ليس لديك حساب؟', 'auth.create_title' => 'أنشئ حسابك',
            'auth.name' => 'الاسم الكامل', 'auth.age' => 'العمر (اختياري)', 'auth.confirm' => 'تأكيد كلمة المرور',
            'auth.register_btn' => 'إنشاء حساب', 'auth.have_account' => 'لديك حساب بالفعل؟',
            'auth.check_email' => 'تحقق من بريدك', 'auth.check_email_text' => 'أرسلنا رابط التحقق إلى', 'auth.goto_signin' => 'الذهاب لتسجيل الدخول',
            'contact.title' => 'تواصل معنا', 'contact.subtitle' => 'أسئلة أو أفكار أو مشكلة في أداة — أرسل رسالة وسنرد عليك.',
            'contact.name' => 'اسمك', 'contact.email' => 'بريدك الإلكتروني', 'contact.subject' => 'الموضوع',
            'contact.message' => 'رسالتك', 'contact.send' => 'إرسال الرسالة', 'contact.sent' => 'تم إرسال الرسالة — شكرًا لك!',
            'account.title' => 'حسابي', 'account.profile' => 'الملف الشخصي', 'account.plan' => 'باقتك',
            'account.credits' => 'رصيد هذه الدورة', 'account.no_plan' => 'ليس لديك باقة بعد.',
            'account.choose_plan' => 'اختر باقة', 'account.cancel' => 'إلغاء الاشتراك',
            'ws.back' => 'كل الأدوات', 'ws.result' => 'النتيجة', 'ws.download' => 'تحميل', 'ws.copy' => 'نسخ',
            'ws.copied' => 'تم النسخ!', 'ws.working' => 'جارٍ العمل…', 'ws.previous' => 'النتائج السابقة',
            'ws.empty' => 'ستظهر نتائجك هنا.',
            'tool.ai-image-generator.name' => 'مولّد الصور بالذكاء الاصطناعي', 'tool.ai-image-generator.desc' => 'حوّل الكلمات إلى صور مذهلة.',
            'tool.ai-content-writer.name' => 'كاتب المحتوى الذكي', 'tool.ai-content-writer.desc' => 'مدونات وإعلانات ورسائل — في ثوانٍ.',
            'tool.ai-translator.name' => 'المترجم الذكي', 'tool.ai-translator.desc' => 'ترجمات طبيعية بأكثر من 12 لغة.',
            'tool.ai-document-assistant.name' => 'مساعد المستندات الذكي', 'tool.ai-document-assistant.desc' => 'ارفع مستندًا واسأله ما تشاء.',
            'tool.ai-background-removal.name' => 'إزالة الخلفية بالذكاء الاصطناعي', 'tool.ai-background-removal.desc' => 'قصّ نظيف بنقرة واحدة.',
            'tool.ai-text-to-audio.name' => 'تحويل النص إلى صوت', 'tool.ai-text-to-audio.desc' => 'تعليق صوتي واقعي من النص.',
            'tool.ai-chat-assistant.name' => 'مساعد الدردشة الذكي', 'tool.ai-chat-assistant.desc' => 'اسأل أي شيء — مساعدك اليومي.',
            'tool.ai-text-rewriter.name' => 'القواعد وإعادة الصياغة', 'tool.ai-text-rewriter.desc' => 'صحّح أو أعد صياغة النص بنقرة.',
            'tool.ai-summarizer.name' => 'الملخّص الذكي', 'tool.ai-summarizer.desc' => 'نص طويل يدخل، أفكار رئيسية تخرج.',
        ];
        $ext_fr = [
            'auth.welcome' => 'Bon retour', 'auth.signin_sub' => 'Connectez-vous à votre studio.',
            'auth.email' => 'E-mail', 'auth.password' => 'Mot de passe', 'auth.signin_btn' => 'Se connecter',
            'auth.no_account' => "Pas encore de compte ?", 'auth.create_title' => 'Créez votre compte',
            'auth.name' => 'Nom complet', 'auth.age' => 'Âge (facultatif)', 'auth.confirm' => 'Confirmer le mot de passe',
            'auth.register_btn' => 'Créer un compte', 'auth.have_account' => 'Vous avez déjà un compte ?',
            'auth.check_email' => 'Vérifiez vos e-mails', 'auth.check_email_text' => 'Nous avons envoyé un lien de vérification à', 'auth.goto_signin' => 'Aller à la connexion',
            'contact.title' => 'Contactez-nous', 'contact.subtitle' => "Questions, idées ou souci avec un outil — envoyez un message, nous vous répondrons.",
            'contact.name' => 'Votre nom', 'contact.email' => 'Votre e-mail', 'contact.subject' => 'Sujet',
            'contact.message' => 'Votre message', 'contact.send' => 'Envoyer', 'contact.sent' => 'Message envoyé — merci !',
            'account.title' => 'Mon compte', 'account.profile' => 'Profil', 'account.plan' => 'Votre offre',
            'account.credits' => 'Crédits de ce cycle', 'account.no_plan' => "Vous n'avez pas encore d'offre.",
            'account.choose_plan' => 'Choisir une offre', 'account.cancel' => "Annuler l'abonnement",
            'ws.back' => 'Tous les outils', 'ws.result' => 'Résultat', 'ws.download' => 'Télécharger', 'ws.copy' => 'Copier',
            'ws.copied' => 'Copié !', 'ws.working' => 'En cours…', 'ws.previous' => 'Résultats précédents',
            'ws.empty' => 'Vos résultats apparaîtront ici.',
            'tool.ai-image-generator.name' => "Générateur d'Images IA", 'tool.ai-image-generator.desc' => 'Transformez des mots en visuels superbes.',
            'tool.ai-content-writer.name' => 'Rédacteur IA', 'tool.ai-content-writer.desc' => 'Blogs, pubs, e-mails — rédigés en secondes.',
            'tool.ai-translator.name' => 'Traducteur IA', 'tool.ai-translator.desc' => 'Traductions naturelles en 12+ langues.',
            'tool.ai-document-assistant.name' => 'Assistant Documents IA', 'tool.ai-document-assistant.desc' => 'Téléversez un document et interrogez-le.',
            'tool.ai-background-removal.name' => "Suppression d'Arrière-plan IA", 'tool.ai-background-removal.desc' => 'Détourage propre en un clic.',
            'tool.ai-text-to-audio.name' => 'Texte vers Audio IA', 'tool.ai-text-to-audio.desc' => 'Voix off réalistes à partir de texte.',
            'tool.ai-chat-assistant.name' => 'Assistant de Chat IA', 'tool.ai-chat-assistant.desc' => "Demandez n'importe quoi — votre aide quotidienne.",
            'tool.ai-text-rewriter.name' => 'Grammaire et Réécriture IA', 'tool.ai-text-rewriter.desc' => 'Corrigez ou réécrivez en un clic.',
            'tool.ai-summarizer.name' => 'Résumeur IA', 'tool.ai-summarizer.desc' => 'Texte long en entrée, points clés en sortie.',
        ];
        $en = array_merge($en, $ext_en);
        $es = array_merge($es, $ext_es);
        $zh = array_merge($zh, $ext_zh);
        $ar = array_merge($ar, $ext_ar);
        $fr = array_merge($fr, $ext_fr);

        foreach ([
            ['code' => 'en', 'name' => 'English', 'native_name' => 'English', 'dir' => 'ltr', 'sort_order' => 1, 'translations' => $en],
            ['code' => 'es', 'name' => 'Spanish', 'native_name' => 'Español', 'dir' => 'ltr', 'sort_order' => 2, 'translations' => $es],
            ['code' => 'zh', 'name' => 'Mandarin Chinese', 'native_name' => '中文', 'dir' => 'ltr', 'sort_order' => 3, 'translations' => $zh],
            ['code' => 'ar', 'name' => 'Arabic', 'native_name' => 'العربية', 'dir' => 'rtl', 'sort_order' => 4, 'translations' => $ar],
            ['code' => 'fr', 'name' => 'French', 'native_name' => 'Français', 'dir' => 'ltr', 'sort_order' => 5, 'translations' => $fr],
        ] as $lang) {
            Language::updateOrCreate(['code' => $lang['code']], $lang + ['enabled' => true, 'is_custom' => false]);
        }
    }
}
